name: CI Pipeline for UI Tests

on:
  push:
    branches:
      - master  # Запускать pipeline при пуше в ветку main
  pull_request:
    branches:
      - master  # Запускать pipeline при создании pull request в ветку main

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Используем последнюю версию Ubuntu

    steps:
      # Шаг 1: Клонируем репозиторий
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Устанавливаем Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Указываем версию Java
          distribution: 'temurin'  # Используем Temurin (Adoptium)


      # Шаг 4: Запускаем тесты с помощью Maven
      - name: Run tests with Maven
        run: mvn clean test